version: '3.6'

services:

  db:
    image: mysql:5.7.28
    container_name: mysql
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - "~/var/data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret

  redis:
    image: redis:5.0-alpine
    container_name: redis
    command: --appendonly yes
    ports:
      - "6379:6379"
    restart: always

  redis-cluster:
    image: grokzen/redis-cluster:latest
    container_name: redis-cluster
    environment:
      IP: '0.0.0.0'
      SENTINEL: 'false'
      STANDALONE: 'false'
    hostname: server
    ports:
      - '7000-7050:7000-7050'
      - '5000-5010:5000-5010'
